/** Explicitly illustrative preview data. Never imported by a production entry point. */
export const worldId = "preview-deutschland";
export const operatorId = "nordlicht-bahn";
export const playerContext = {schemaVersion:"zugfolge-operator-context/v1",worldId,operators:[{id:operatorId,name:"Nordlicht Bahn",finance:{mode:"finite",ledgerBalanceCents:"250000000",pendingDebitCents:"5000000",availableCents:"245000000"}}]};
export const worldContract = {schemaVersion:"zugfolge-public-world-contract/v1",contractHash:"a".repeat(64),worldId,name:"Deutschland",region:{id:"de",name:"Deutschland",variant:"2026"},noWipe:true,schedulePeriodWeeks:4,duration:{kind:"unlimited"},timeBasis:{mode:"realtime",accelerationFactor:1,epoch:"2026-09-01T00:00:00Z",timeZone:"Europe/Berlin"},entry:{status:"open",requiresContractConfirmation:true,opensAt:"2026-09-01T00:00:00Z",closesAt:null},startingCapitalPolicy:{kind:"finite",amountCents:"250000000"},releases:{infra:"b".repeat(64),timetable:"c".repeat(64),fleet:"d".repeat(64),economy:"e".repeat(64)}};
export const cities = [{name:"Hamburg",p:[9.994,53.552]},{name:"Berlin",p:[13.369,52.525]},{name:"Bremen",p:[8.813,53.083]},{name:"Hannover",p:[9.742,52.378]},{name:"Köln",p:[6.958,50.943]},{name:"Frankfurt",p:[8.663,50.107]},{name:"Leipzig",p:[12.382,51.345]},{name:"Dresden",p:[13.731,51.04]},{name:"Nürnberg",p:[11.082,49.447]},{name:"Stuttgart",p:[9.182,48.784]},{name:"München",p:[11.559,48.14]},{name:"Kiel",p:[10.131,54.315]},{name:"Rostock",p:[12.132,54.078]},{name:"Erfurt",p:[11.038,50.972]},{name:"Dortmund",p:[7.46,51.517]},{name:"Kassel",p:[9.447,51.313]},{name:"Freiburg",p:[7.841,47.998]}];
export const corridors = [[0,3],[0,2],[0,1],[0,11],[0,12],[12,1],[2,3],[3,1],[3,14],[14,4],[3,15],[15,5],[5,4],[5,9],[9,10],[10,8],[8,13],[13,6],[6,1],[6,7],[7,1],[5,13],[8,5],[9,16]];
export const trains = corridors.map(([from,to],index)=>{const a=cities[from],b=cities[to];const t=.3+(index%4)*.12;const p=[a.p[0]+(b.p[0]-a.p[0])*t,a.p[1]+(b.p[1]-a.p[1])*t];return {id:`zug-${index}`,operatorId:index%3===0?operatorId:"horizont",operator:index%3===0?"Nordlicht Bahn":"Horizont Verkehr",trainNumber:index===0?"IC 2084":`${index%3===0?"IC":"RE"} ${7+index*3}`,category:index%3===0?"Fernverkehr":"Regionalverkehr",positionMm:1000000,speedMmPerSecond:22000,delaySeconds:index===0?180:index%7===0?360:0,nextOperatingPoint:`${b.name} Hbf`,status:index%5===0?"at_platform":"running",mapPosition:{infrastructureReleaseId:"preview-infra",resourceId:`block-${index}`,trackId:`track-${index}`,offsetMm:1000000,latitudeE7:Math.round(p[1]*1e7),longitudeE7:Math.round(p[0]*1e7)}};});
export const mailbox = [{id:"mail-1",worldId,messageType:"cooperation.contract-offer",payload:{title:"Fahrzeugmiete: Deine Antwort zählt",contractId:"vertrag-1"},sentAt:"2026-09-05T08:00:00Z",deadlineAt:"2026-09-06T18:00:00Z",acknowledgedAt:null,priority:"due-soon",overdue:false},{id:"mail-2",worldId,messageType:"vehicle-market.reserved",payload:{title:"Ein Fahrzeug wartet auf die Übergabe",listingId:"listing-1"},sentAt:"2026-09-05T09:15:00Z",deadlineAt:null,acknowledgedAt:null,priority:"information",overdue:false}];
export const vehicles = [442,463,146,612].map((n,i)=>({worldId,vehicleId:`NL-${String(i+1).padStart(3,"0")}`,classDesignation:`Baureihe ${n}`,ownerOperatorId:operatorId,holderOperatorId:operatorId,odometerMetres:String(380000000+i*32500000),conditionBasisPoints:9600-i*300,damages:[],maintenanceDeadlines:i===2?[{kind:"inspection"}]:[],bindings:{},valueCents:String(220000000-i*20000000),revision:1,historyHash:"f".repeat(64)}));
export const cooperation = {worldId,worldName:"Deutschland",activeOperatorId:operatorId,operators:[{id:operatorId,worldId,name:"Nordlicht Bahn"},{id:"horizont",worldId,name:"Horizont Verkehr"}],ownOperatorIds:[operatorId],contracts:[],listings:[],ownedVehicles:vehicles,resources:{schemaVersion:"zugfolge-cooperation-resource-catalog/v1",worldId,operatorId,fleetRevision:7,fleetSnapshotHash:"f".repeat(64),trainRuns:[],connectionTrainRuns:[],formations:[{id:"formation-1",label:"Baureihe 442 · 4 Wagen",detail:"Regionalverkehr · einsatzbereit"}],publicEntryFacilities:[],personnelDuties:[],pathReceipts:[],disruptions:[],rentableVehicles:[],assistanceVehicles:[]},stationOptions:cities.map(city=>({id:city.name.toLowerCase(),label:`${city.name} Hbf`})),contractType:"traction",marketQuery:"",contractPageView:"actionable",listingPageView:"actionable",contractNextCursor:null,listingNextCursor:null,atS:4*86400+14*3600,busy:false,tenders:[],section:"markets"};
export const program = {schema:"operating-program/v1",world_id:worldId,operator_id:operatorId,version:1,enabled:true,rules:[{id:"anschluss-halten",priority:300,enabled:true,trigger:{type:"connection_risk"},condition:{type:"predicate",fact:"connection_threatened",comparison:"equal",value:{type:"boolean",value:true}},action:"hold_connection"},{id:"zug-umleiten",priority:200,enabled:true,trigger:{type:"route_closure"},condition:{type:"predicate",fact:"route_closed",comparison:"equal",value:{type:"boolean",value:true}},action:"request_reroute"}]};
cooperation.tenders = [{id:"tender-1",lotId:"re3",phase:"open",bidCount:3,ownBidCount:0,closesAt:cooperation.atS+86400,serviceLines:[{designation:"RE 3",origin:"Hamburg Hbf",destination:"Hannover Hbf"}]},{id:"tender-2",lotId:"re9",phase:"open",bidCount:2,ownBidCount:0,closesAt:cooperation.atS+86400,serviceLines:[{designation:"RE 9",origin:"München Hbf",destination:"Nürnberg Hbf"}]}];
cooperation.listings = [442,463].map((number,index)=>({id:`angebot-${index}`,worldId,vehicleId:`HZ-${number}`,offeringOperatorId:"horizont",listingType:index===0?"sale":"rental",priceCents:index===0?"175000000":"650000",disclosure:{classDesignation:`Baureihe ${number}`,conditionBasisPoints:index===0?9400:9700,odometerMetres:"128600000",damages:[],maintenanceDeadlines:[],approvals:["Deutschland"],seats:320,historyHash:"b".repeat(64)},disclosureHash:"c".repeat(64),listedAtS:cooperation.atS-3600,expiresAtS:cooperation.atS+86400,status:"open",revision:1}));
cooperation.contracts = [{id:"vertrag-1",worldId,offerorOperatorId:"horizont",offereeOperatorId:operatorId,contractType:"vehicle-rental",subject:{vehicleId:"HZ-463"},terms:{},termsHash:"a".repeat(64),priceCents:"650000",validFromS:cooperation.atS+3600,validUntilS:cooperation.atS+86400*7,responseDeadlineS:cooperation.atS+86400,terminationNoticeS:3600,status:"offered",offeredAtS:cooperation.atS-3600,revision:1}];
export const decisions = [{decisionId:"d-1",sequence:241,trainRunId:"IC 2084",action:"hold_connection",cause:"Verspätete Ankunft",causeCode:null,causeLabel:"",fineCauseId:null,fineCauseLabel:null,affectedResource:"Hannover Hbf",outcomeReason:"Anschluss wartet bis zu 3 Minuten",impact:{cost_cents:15000}},{decisionId:"d-2",sequence:240,trainRunId:"RE 28",action:"request_reroute",cause:"Bauarbeiten",causeCode:null,causeLabel:"",fineCauseId:null,fineCauseLabel:null,affectedResource:"Frankfurt Hbf",outcomeReason:"Freie Alternativstrecke angefragt",impact:{cost_cents:24000}}];
export const operationsState = {worldId,operatorId,activePanel:"operations",pageUrl:"http://127.0.0.1:4173/?screen=operations",gameWebUrl:"http://127.0.0.1:4173/",livemapUrl:"http://127.0.0.1:4173/?screen=map",operatorContext:playerContext,program,savedProgram:{version:1,status:"active",checksum:"a".repeat(64),canonicalProgram:program},templates:[{id:"everyday",name:"Entspannt durch den Alltag",program}],versions:[{version:1,status:"active",checksum:"a".repeat(64),canonicalProgram:program}],operations:{throughSequence:241,consumerAvailable:true,decisions,cancellations:[],manualInterventions:[],majorEvents:[decisions[1]]},reports:[],loading:false,saving:false,message:"",messageTone:"status",selectedDecisionId:""};
