import { interpolatedPosition, LivemapConnection, type LiveState, type PublicTrain } from "./protocol.js";
import "./style.css";
let trains: PublicTrain[] = [];
let receivedAt = performance.now();
let renderGeneration=0;
const root=document.querySelector<HTMLDivElement>("#root")!;
root.innerHTML=`<main><header><span class="wordmark">ZUGFOLGE</span><span>Livemap · Welt Leipzig–Halle–Erfurt</span><time>verbinde …</time></header><section class="workspace"><div class="map" aria-label="Livemap"><svg viewBox="0 0 1000 520" role="img"><title>Streckennetz und aktuelle Zugpositionen</title><path class="context" d="M30 430 L200 350 L370 365 L520 250 L750 180 L970 70"/><path class="rail" d="M60 420 L260 330 L450 345 L620 220 L940 90"/><path class="rail secondary" d="M450 345 L590 440 L820 460"/><g id="trains"></g></svg><div class="legend"><span>● Betrieb</span><span class="delay">● Abweichung</span><span class="contextText">― Kontextnetz</span></div></div><aside><p class="eyebrow">ZUGLAUF</p><p>Eine Zugfahrt auswählen.</p></aside></section></main>`;
function select(id:string){const train=trains.find(item=>item.id===id)!;document.querySelectorAll(".train").forEach(node=>node.classList.toggle("selected",(node as SVGElement).dataset.id===id));document.querySelector("aside")!.innerHTML=`<p class="eyebrow">ZUGLAUF</p><h1>${train.trainNumber}</h1><p>${train.operator} · ${train.category}</p><dl><dt>Status</dt><dd>${train.status==="waiting"?"wartet":"unterwegs"}</dd><dt>Verspätung</dt><dd class="${train.delaySeconds>180?"warn":""}">+${Math.floor(train.delaySeconds/60)} min</dd><dt>Geschwindigkeit</dt><dd>${Math.floor(train.speedMmPerSecond/1000*3.6)} km/h</dd><dt>Nächster Betriebspunkt</dt><dd>${train.nextOperatingPoint}</dd></dl><div class="route"><b>Leipzig Hbf</b><span class="done">ab 14:04</span><b>${train.nextOperatingPoint}</b><span>an 14:38</span><b>Erfurt Hbf</b><span>an 15:27</span></div>`;}
function draw(state:LiveState){const renderAt=state.at+Math.min((performance.now()-receivedAt)/1000,10);document.querySelector("#trains")!.innerHTML=trains.map((item,index)=>{const position=interpolatedPosition(item,state.at,renderAt);return `<g data-id="${item.id}" transform="translate(${100+(position%800_000_000)/1_000_000} ${160+(index%4)*75})" class="train ${item.status}"><circle r="11"/><text x="18" y="5">${item.trainNumber}</text></g>`;}).join("");document.querySelectorAll<SVGGElement>(".train").forEach(node=>node.addEventListener("click",()=>select(node.dataset.id!)));}
function render(state:LiveState){trains=[...state.trains.values()];receivedAt=performance.now();renderGeneration+=1;const generation=renderGeneration;document.querySelector("time")!.textContent=`Sequenz ${state.sequence}`;draw(state);let previous=performance.now();const animate=(now:number)=>{if(generation!==renderGeneration)return;if(now-previous>=250){draw(state);previous=now;}if(performance.now()-receivedAt<10_000)requestAnimationFrame(animate);};requestAnimationFrame(animate);}
const parameters=new URLSearchParams(location.search);const worldId=parameters.get("world")??"00000000-0000-0000-0000-000000000001";const connection=new LivemapConnection(parameters.get("api")??"",worldId,render);void connection.connect().catch(error=>{document.querySelector("time")!.textContent="Verbindung unterbrochen";console.error(error);});window.addEventListener("beforeunload",()=>connection.close());
